### ISSUE TITLE
"me" route returns "Invalid token"

### ISSUE THREAD

**Issue by DonLiborio** [jmrhib/satellizer-slim-backend#1]
First, let me thank you once again, this is great!

Now the issues begin. I'm using satellizer example client (I only changed $authProvider.baseUrl to '/api')  and satellizer-slim-backend as it is. I only added my facebook secret and database connection information to Config.php.

I can get my app to login, and I can see the database is populated with the new user info. I can log in and out. However, I can't get the "me" route to work, it just returns "Invalid token", although I think Satellizer is sending the token.

I'm sure I'm missing something...

**Comment by DonLiborio** [comment]
I figured that if I change Satellizer's default configuration from:

```
$authProvider.authToken = 'Bearer';
```

to

```
$authProvider.authToken = '';
```

the "/me" route works.

**Comment by jmrhib** [comment]
Seems to be that Satellizer has added the option to put a prefix (authToken) on the Authorization header. This backend, and (as it seems) the Laravel PHP example does not take into account such a prefix.

See:
https://github.com/sahat/satellizer/pull/333
https://github.com/sahat/satellizer/issues/525

So, yes, the solution is probably what you have done.
